### PR TITLE
chore: fix build and wrapper generation & regenerate

### LINKED ISSUE #7: Clean up 🧹  Clean up contracts
PR https://github.com/celestiaorg/quantum-gravity-bridge/pull/3 introduced a bunch of changes that broke the build. Not only because the go-code wasn't updated but because of not regenerating the go-wrappers and moving around directories (ctx: https://github.com/celestiaorg/quantum-gravity-bridge/pull/3#discussion_r748835873). 

First, the Makefile needs to be updated accordingly:
https://github.com/celestiaorg/quantum-gravity-bridge/blob/e2a253f47dbf6ebeee277d6e340f7bfb42b47e39/Makefile#L69-L70

Note that after fixing the paths in the Makefile to `SOLIDITY_DIR = ethereum/solidity` things are still broken:
```
abigen --type=peggy --pkg wrappers --out=../wrappers/TestERC20.sol/wrapper.go --sol TestERC20.sol
Fatal: Failed to build Solidity contract: solc: exit status 1
Error: Source "@openzeppelin/contracts/utils/cryptography/ECDSA.sol" not found: File not found.
 --> QuantumGravityBridge.sol:5:1:
  |
5 | import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "@openzeppelin/contracts/proxy/utils/Initializable.sol" not found: File not found.
 --> OwnableUpgradeableWithExpiry.sol:6:1:
  |
6 | import "@openzeppelin/contracts/proxy/utils/Initializable.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "@openzeppelin/contracts/proxy/utils/Initializable.sol" not found: File not found.
 --> ContextUpgradeable.sol:5:1:
  |
5 | import "@openzeppelin/contracts/proxy/utils/Initializable.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Fatal: Failed to build Solidity contract: solc: exit status 1
Error: Source "@openzeppelin/contracts/token/ERC20/ERC20.sol" not found: File not found.
 --> TestERC20.sol:5:1:
  |
5 | import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


make: *** [solidity-wrappers] Error 1
Fatal: Failed to build Solidity contract: solc: exit status 1
Error: Source "@openzeppelin/contracts/token/ERC20/ERC20.sol" not found: File not found.
 --> TestERC20.sol:5:1:
  |
5 | import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'm investigating.

### PR DESCRIPTION
**Pull request by liamsi**
Tests will still fail but at least the build works again.

Fixes #7

### CODE REVIEW

**Comment by liamsi** [comment]
There are still some things to fix. Hence back to draft.

File: orchestrator/cosmos/broadcast.go [hunk 1]
```diff
@@ -77,11 +55,8 @@ type PeggyBroadcastClient interface {
 // sortableEvent exists with the only purpose to make a nicer sortable slice for Ethereum events.
 // It is only used in SendEthereumClaims
 type sortableEvent struct {
-	EventNonce         uint64
-	DepositEvent       *wrappers.PeggySendToCosmosEvent
-	WithdrawEvent      *wrappers.PeggyTransactionBatchExecutedEvent
-	ValsetUpdateEvent  *wrappers.PeggyValsetUpdatedEvent
-	ERC20DeployedEvent *wrappers.PeggyERC20DeployedEvent
+	EventNonce        uint64
+	ValsetUpdateEvent *wrappers.QuantumGravityBridgeValidatorSetUpdatedEvent
```
Comment (adlerjohn) [inline orchestrator/cosmos/broadcast.go:59]: The event `PeggyTransactionBatchExecutedEvent` was renamed in the contract to `MessageTupleRootEvent`. You could argue it's the only actual critical part of the contracts that needed to be modified. This PR is fine I think, but we need to replace the function that watched for `PeggyTransactionBatchExecutedEvent` with one that watches for `MessageTupleRootEvent` in the relayer (not sure why it's under the orchestrator).

File: orchestrator/relayer/batch_relaying.go [hunk 2]
```diff
@@ -1,89 +1 @@
...
-	"context"
-
-	"github.com/ethereum/go-ethereum/common"
-	"github.com/pkg/errors"
-	"github.com/umee-network/umee/x/peggy/types"
-)
-
-// RelayBatches checks the last validator set on Ethereum, if it's lower than our latest valida
-// set then we should package and submit the update as an Ethereum transaction
-func (s *peggyRelayer) RelayBatches(ctx context.Context) error {
```
Comment (adlerjohn) [inline orchestrator/relayer/batch_relaying.go:13]: This is probably what we want to replace with code to relay message tuple roots.

**Review by adlerjohn — APPROVED** [review]
Lots of commented-out code, but that's fine. Should have enough info just from that to know where modifications need to be done.

File: orchestrator/relayer/batch_relaying.go (hunk 2 above)
Comment (liamsi) [reply orchestrator/relayer/batch_relaying.go:13]: Yeah, I but I feel this PR was already way, way too large 😬 

There are a few things that need to be done:
 - [ ] integration tests need to be cleaned up
 - [ ] message tuple roots creating and add in that method here (above) and in the corresponding interface
 - [ ] ValeSetRootHash needs to be created (note that the validators here used do additionally sign the valsetUpdates with a different signing key from the tendermint one as far as I understand; just noting that as it might be easier to keep it that way instead of changing everything to ecdsa in tendermint directly)
 - [ ] ...
